### ISSUE TITLE
Missing scripture location for Hab Dreyko

### ISSUE THREAD

**Issue by highlyunavailable** [manschko/Darktide-Collectible#3]
https://manschko.github.io/Darktide-Collectible/HL-16-11/Hab Dreyko/Scriptures

It shows up very near to this med station right before the final "group up" room that takes you down to the final section.

![20221204224228_1](https://user-images.githubusercontent.com/6266125/205567863-a33b64f6-f95c-45fa-9d93-7dbb7c7a48cb.jpg)

**Comment by manschko** [comment]
Might you remember the exact location where it would spawn ?
