### ISSUE TITLE
Missions Fail To Populate On Navigating Back

### ISSUE THREAD

**Issue by nnickodem** [manschko/Darktide-Collectible#4]
When you already have reached a scripture/grimoire page, and click the back button, the mission dropdown fails to populate even though a real location is already selected

**Comment by nnickodem** [comment]
also presuming you guys see this, looks like making PRs/branches is no longer open to the public, so could the google form be linked in the README?

**Comment by manschko** [comment]
Interesting, I will try working on a fix. Pull request should still be open, I didn't change anything and I got a pull request yesterday

**Comment by manschko** [comment]
Should be fixed. If the problem still persists, please let me know
